version: '3'
services:
  #definidos manualmente
  ms-main:
    image: 'ms-main'
    container_name: cn_ms_main
    depends_on:
      - ms-redis-mq
    ports:
    - "80:80"
    networks:
      - syner-red
    environment:
    - LOCAL_PORT_DATABASE=3306
    volumes:
      - volume-main-source-code:/usr/src/app
  
  #hacia abajo definidos en docker-hub  
  ms-redis-mq:
    image: redis:6.0
    container_name: cn_ms_redis
    volumes:
      - volume-redis-mq:/etc/rabbitmq    
    ports:
      - 6380:6379
    networks:
      - syner-red
networks:
  syner-red:
    driver: bridge
volumes:  
  volume-main-source-code:
  volume-redis-mq:
